import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Provider from "./hooks/themeProvider";
import Navbar from "./components/Navbar";
import { CoinContext } from "./context/coinDataContext";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import { Open_Sans } from "next/font/google";
import MobileFooter from "./components/MobileFooter";

export const metadata: Metadata = {
  title: "Crypto App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you need
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.className} dark:bg-[#13121A] bg-[#f5f5f5] min-h-screen`}
        suppressHydrationWarning
      >
        <CoinContext>
          <ThemeProvider attribute="class">
            <Navbar />

            {children}
            <MobileFooter />
          </ThemeProvider>
        </CoinContext>
      </body>
    </html>
  );
}
